// animals.js
export const ANIMALS = [
  {
    id: "cow",
    name: "Cow",
    color: "#FFB703",
    image: require("./assets/animals/cow.png"),
    sound: require("./assets/animals/cow.mp3"),
  },
  {
    id: "goat",
    name: "Goat",
    color: "#8ECAE6",
    image: require("./assets/animals/goat.png"),
    sound: require("./assets/animals/goat.mp3"),
  },
  {
    id: "wolf",
    name: "Wolf",
    color: "#9D8DF1",
    image: require("./assets/animals/wolf.png"),
    sound: require("./assets/animals/wolf.mp3"),
  },
  {
    id: "horse",
    name: "Horse",
    color: "#FB8500",
    image: require("./assets/animals/horse.png"),
    sound: require("./assets/animals/horse.mp3"),
  },
  {
    id: "donkey",
    name: "Donkey",
    color: "#90BE6D",
    image: require("./assets/animals/donkey.png"),
    sound: require("./assets/animals/donkey.mp3"),
  },
  {
    id: "elephant",
    name: "elephant",
    color: "#F4978E",
    image: require("./assets/animals/elephant.png"),
    sound: require("./assets/animals/elephant.mp3"),
  },
  {
    id: "dog",
    name: "Dog",
    color: "#43AA8B",
    image: require("./assets/animals/dog.png"),
    sound: require("./assets/animals/dog.mp3"),
  },
  {
    id: "cat",
    name: "Cat",
    color: "#F9C74F",
    image: require("./assets/animals/cat.png"),
    sound: require("./assets/animals/cat.mp3"),
  },
  {
    id: "frog",
    name: "Frog",
    color: "#52B788",
    image: require("./assets/animals/frog.png"),
    sound: require("./assets/animals/frog.mp3"),
  },
  {
    id: "hen",
    name: "Hen",
    color: "#FF9F1C",
    image: require("./assets/animals/hen.png"),
    sound: require("./assets/animals/hen.mp3"),
  },
  {
    id: "sparrow",
    name: "Sparrow",
    color: "#90E0EF",
    image: require("./assets/animals/sparrow.png"),
    sound: require("./assets/animals/sparrow.mp3"),
  },
  {
    id: "crow",
    name: "Crow",
    color: "#ADB5BD",
    image: require("./assets/animals/crow.png"),
    sound: require("./assets/animals/crow.mp3"),
  },
];
